# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-08 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='isRegisted',
            field=models.IntegerField(default='1'),
        ),
    ]
