# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-07 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LivePhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jpg_dic', models.CharField(max_length=200)),
                ('mov_dic', models.CharField(max_length=200)),
                ('uploader', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('describe', models.CharField(max_length=200)),
            ],
        ),
    ]
