# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-07 13:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livephoto',
            name='jpg_dic',
        ),
        migrations.RemoveField(
            model_name='livephoto',
            name='mov_dic',
        ),
    ]
