# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-07 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_auto_20170507_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='livephoto',
            name='filename',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='livephoto',
            name='describe',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='livephoto',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='livephoto',
            name='uploader',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
