# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-08 04:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_auto_20170507_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='livephoto',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='livephoto',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
