# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-08 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0004_auto_20170508_0411'),
    ]

    operations = [
        migrations.AddField(
            model_name='livephoto',
            name='file_location',
            field=models.FileField(null=True, upload_to='./static/upload/'),
        ),
    ]
