# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-08 05:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0005_livephoto_file_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livephoto',
            name='file_location',
        ),
    ]
